apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: csi-image-extractor
spec:
  # Recommondation: use multi-node attachable RWX storageClass
  storageClassName: csi-manila-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi