apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: busybox
    volumeMounts:
    - name: data
      mountPath: /container-image-data
  volumes:
  - name: data
    csi:
      driver: image.csi.cnmp.sap
      volumeAttributes:
        # Specify your image here. busybox used just as a placeholder, not
        # because its a good idea. See the container folder for a better
        # example.
        image: busybox
